country_tuple = ("Philippines", "Thailand", "Indonesia", "Malaysia", "Vietnam")
print(country_tuple)
print()
country = input("Please enter one of the countries from above: ")
print(country, "has index number", country_tuple.index(country))